name: 打包应用的actions
on:
  push: # 监听代码时间
    branches:
      - master # master分支代码推送的时候激活当前action
jobs:
  build:
    # runs-on 操作系统
    runs-on: ubuntu-latest
    steps:
      # Job Start
      - name: Job Start
        run: echo Hello, GitHub workflows !

      # 检出你在当前github工作空间的项目
      - name: 迁出代码
        uses: actions/checkout@v2

      # 安装Node
      - name: 安装Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      # 安装依赖
      - name: 安装依赖
        run: npm install

      # 打包
      - name: 打包
        run: npm run build

      # 执行JamesIves/github-pages-deploy-action将项目发布到Github Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          # # 部署到你的目标仓库，这里就是你的仓库名
          # REPO: git@github.com:owner/repo.git
          # 该workflow需要操作repo，因此需要一个密钥，下面会讲到如何获取这个密钥
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # 发布到的分支
          BRANCH: master
          # 要发布的文件夹
          FOLDER: blog/.vuepress/dist
